- src/LibLog.Tests/LogProviders/ColouredConsoleProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/SerilogLogProviderLoggingTests.cs
- src/LibLog/LibLog.cs
It appears that EntLib Logging [doesn't support the concept](https://entlib.codeplex.com/discussions/3523); though this is out of date, if anyone knows if it's possible, please let me know how.
LoupeLog support: awaiting response from @kendallmiller on pointers on how to.
> Diagnostic context support (NDC and MDC) with implementations for NLog, Log4Net and Serilog

- src/LibLog.Tests/LogProviderTests.cs
- src/LibLog/LibLog.cs
Thanks for the great work on this project! I've found it really useful.
I needed PCL compatibility for a project at work. I've made a few changes for this.
* `#define PORTABLE` omits the `GetCurrentClassLogger()` method from the PCL version because this uses `StackFrame`, which is not available. This is commented out by default.
* No longer references `System.Diagnostics.TraceEventType` directly. Uses reflection instead.
* No longer references `System.Console` directly. Uses reflection instead.
* No longer references `System.ConsoleColor` directly. Uses reflection instead.
Please let me know if you think this is a sensible method of achieving PCL support.
It could make it smoother for nuget consumers if there were two versions of the file in the package. 
* One with `#define PORTABLE` …
> Made LibLog PCL compatible. Related to issue #9.

- src/LibLog.Tests/LogProviders/ColouredConsoleProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/EntLibLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog/LibLog.cs
If you logged a message **without** format parameters, it would still go through String.Format. 
By checking for parameters.Any(), it no longer does this.
> Fixed curly braces logging issue

- src/LibLog/LibLog.cs
YOLO'd via the GitHub UI
fixes #52
> Prevent inlining of GetCurrentClassLogger

- src/LibLog.Tests/LibLogPCL.Tests.csproj
- src/LibLog.Tests/LogProviderTests.cs
- src/LibLog/LibLog.cs
- src/LibLog/LibLog.nuspec
- src/SharedAssemblyInfo.cs
Addresses #50 
Exercised via `YourLib.Logging.LogProvider.IsLoggingEnabled = false`. The `LoggerExecutionWrapper` will check this each call. This means it's safe for both statically initialized logger fields and instance fields/ local instances.
@leastprivilege the issue problem with the Env Var approach is that it will disable Logging for _all_ libraries that use LibLog. Is this desirable / wise? If I could get {YourNamespace}_LIBLOG_DISABLE working, would that be better?
> [WIP] Disable logging at runtime

- default.ps1
- src/LibLog.Tests/LibLog.Tests.csproj
- src/LibLog.Tests/LogProviderTests.cs
- src/LibLog.Tests/LogProviders/ColouredConsoleProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/EntLibLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/LogExtensons.cs
- src/LibLog.Tests/LogProviders/LoupeLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/SerilogLogProviderLoggingTests.cs
- src/LibLog.Tests/LoggerExecutionWrapperTests.cs
- src/LibLog/LibLog.cs
- src/LibLog/LibLog.csproj
- src/LibLog/LibLogPCL.csproj
This is to make it **explicitly** clear that the root namespace should be changed if the user copy-pastes the code.
Normal circumstances, the namespace will change on package install.
> Changes the root namespace from `LibLog` to `YourRootNamespace`

- src/LibLog/LibLog.cs
It is used on the 'Get' API, mostly because of extensions methods over the interface.
Also make LogExtensions partial.
Re- fixes #48.
> Internalize ILog, it's not part of the 'Set' API

- src/LibLog.Example.Log4Net/log4net.config
- src/LibLog/LibLog.cs
Adapted Common.Logging's solution to problem and now the logger name should be correct. Portable version is a lot harder to fix properly as there is no real Stacktrace support.
Now using ILogger interface that gives unified Log method that accepts level and possible exception as parameter. I was then able to clean up the implementation a bit with regards to all if statements and dynamic calls.
fixes #25
> fixes #25 log4net showing wrong type as logger

- src/LibLog.Tests/LogProviders/EntLibLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/LoupeLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/SerilogLogProviderLoggingTests.cs
- src/LibLog/LibLog.cs
The regular expression was being used to SimulateStructuredLogging. The existing regex was not recognizing the @ modifier , used by serilog, that indicates that the parameter should be serialized.
> Fixed the regular expression in LogMessageFormatter 

- src/LibLog/LibLog.cs
In the main Log method, we don't need to access the environment variable if _getIsDisabled() would have returned true. This will speed the non-logging if disabled elsewhere by not checking the environment. This also unifies the code for LIBLOG_PORTABLE as much as possible.
> Don't read the DisableLoggingEnvironmentVariable if already disabled.

- src/LibLog/LibLog.csproj
- src/LibLog/LibLogPCL.csproj
Assuming you want to keep supporting C# 5 folks, this will stop you accidentally not doing so.
> limit to C# 5

- default.ps1
I noticed that the second instance of `YourRootNamespace` wasn't being replaced in the [second code analysis suppression](https://github.com/damianh/LibLog/blob/0ad013fb9c27e76e0138c415c77d9216803fb946/src/LibLog/LibLog.cs#L44).
Rather than add a fourth replacement, I switched to a single replacement which also matches on the trailing `.` which is enough to exclude the [docs line](https://github.com/damianh/LibLog/blob/0ad013fb9c27e76e0138c415c77d9216803fb946/src/LibLog/LibLog.cs#L46) from the replacement.
connects to #89
> fixed missing namespace replacement

- src/LibLog.Tests.NoLogFwkReferences/LibLog.Tests.NoLogFwkReferences.csproj
- src/LibLog.Tests.NoLogFwkReferences/LibLogTests.cs
- src/LibLog.Tests.NoLogFwkReferences/Properties/AssemblyInfo.cs
- src/LibLog.Tests.NoLogFwkReferences/packages.config
- src/LibLog.sln
- src/LibLog/LibLog.cs
- src/LibLog/Properties/AssemblyInfo.cs
> Return a no-op disposable when opening a nested/mapped diagnostic context and no logprovider has been set.

- src/LibLog/LibLog.cs
Hi Mr Hickey,
As a proposed fix for #40 I would like to use [SourceContext](https://github.com/serilog/serilog/wiki/Writing-Log-Events#source-contexts) as the key when calling Serilog's ForContext().
This change brings LibLog in line with how Serilog's other overloads of ForContext() behave when [given a type](https://github.com/serilog/serilog/blob/d97f2b4f6fbd2afe42f3ccebfeef1e431eda239b/src/Serilog/Core/Pipeline/Logger.cs#L97).
In the Serilog library, this constant is defined in [Serilog.Core.Constants.SourceContextPropertyName ](https://github.com/serilog/serilog/blob/d97f2b4f6fbd2afe42f3ccebfeef1e431eda239b/src/Serilog/Core/Constants.cs#L27).
Thanks for your consideration!
Ben Brandt
> SourceContext not outputing correctly in Serilog logger

- ReadMe.md
The shields.io badge hasn't been working for a while and the [related issue](https://github.com/badges/shields/issues/655) isn't seeing much interest from the project owners.
> Switch NuGet badge to buildstats.info

- src/LibLog.Tests.NLog4/LibLog.Tests.NLog4.csproj
- src/LibLog.Tests.NoLogFwkReferences/LibLog.Tests.NoLogFwkReferences.csproj
- src/LibLog.Tests/LibLog.Tests.csproj
- src/LibLog.Tests/LogMessageFormatterTests.cs
- src/LibLog.Tests/app.config
- src/LibLog.Tests/packages.LibLog.Tests.config
- src/LibLog/LibLog.cs
Fixes the following issues with simulating structured logging:
- escaped arguments are not preserved: `{{arg}}` should stay `{{arg}}`
- argument format is not supported: `{arg:yyyy-MM-dd}` should become `{0:yyyy-MM-dd}`)
- if argument is present multiple time, every occurrence has it's own index (`{arg} {arg}` should become `{0} {0}`)
> Fix structured log replacement

- src/LibLog/LibLog.cs
I had a problem with the Release version of the code when using the `GetCurrentClassLogger()`
````
GetLogger(new StackFrame(1, false).GetMethod().DeclaringType);
````
The above code was passing null into GetLogger
This was because it was being called as an argument to a default constructor e.g.,
````
public SomeClass() : this (LogProvider.GetCurrentClassLogger()) {}
````
Debug code was working fine, but release code would throw a null reference exception.
> Include a fallback value for the name for a log in case the type is null

- src/LibLog/LibLog.cs
Currently when writing a structured logging message using log4net, it is simply formatted to a string and written to the log as a string. The user can't take advantage of the structured message containing named parameters.
This pull requests adds the specified named arguments to the Properties of LoggingEvent written to the log: Instead of calling the previously called Log overload of ILogger which that gets all arguments and creates a LoggingEvent - we create a LoggingEvent ourselves and call ILogger's Log overload which receives a LoggingEvent. Before calling it, we populate its Properties property with the structured data. In order to avoid computing the structured data twice, I refactored a bit the LogMessageFormatter and introduced a method there that returns the structured arguments …
> Enable formatted logging for log4net

- src/LibLog.Example.Serilog/LibLog.Example.Serilog.csproj
- src/LibLog.Example.Serilog/packages.config
- src/LibLog.Tests.Serilog2/LibLog.Tests.Serilog2.csproj
- src/LibLog.Tests.Serilog2/LogExtensions.cs
- src/LibLog.Tests.Serilog2/Properties/AssemblyInfo.cs
- src/LibLog.Tests.Serilog2/SerilogLogProviderLoggingTests.cs
- src/LibLog.Tests.Serilog2/packages.config
- src/LibLog.Tests/LibLog.Tests.csproj
- src/LibLog.Tests/LibLogPCL.Tests.csproj
- src/LibLog.Tests/LogProviders/LogExtensions.cs
- src/LibLog.sln
- src/LibLog/LibLog.cs
- src/LibLog/Properties/AssemblyInfo.cs
Serilog example updated to latest versions.
Fixed a typo with log extensions.
Using Serilog 2.2.1
> Serilog 2.X support

- src/LibLog/LibLog.cs
This makes it easy for consumers of LibLog to exclude LibLog.cs from
their code coverage analysis.
>     Add [ExcludeFromCodeCoverage] attribute

- src/LibLog/LibLog.cs
Thanks for Liblog, it's great!
[level]Format and [level]Exception are perfectly fine and work nicely however I believe the method parameters do enough to describe what is happening. 
Which is why I would like 2 extra overloads which do the same as [level]Format and [level]Exception however without "Format" and "Exception".
Its purely a matter of style and I wont be offended if you don't accept this change but I would appreciate it greatly if you could.
Thank you,
Matthew Lyon
> Added formatting overloads

- ReadMe.md
Change `LIBLOB_PORTABLE` to `LIBLOG_PORTABLE`
> Fix readme typo

- src/LibLog/LibLog.cs
There is no need to call Expression.Compile more than once per expression. This pull request moves some of these computations from instance context/message context to static context.
Elad
> Optimizing Expression.Compile computation

- .gitignore
- src/LibLog.Tests.NLog4/LibLog.Tests.NLog4.csproj
- src/LibLog.Tests.Serilog2/LibLog.Tests.Serilog2.csproj
- src/LibLog.Tests.Serilog2/MyMappedContext.cs
- src/LibLog.Tests.Serilog2/SerilogLogProviderLoggingTests.cs
- src/LibLog.Tests/LibLog.Tests.csproj
- src/LibLog.Tests/LibLogPCL.Tests.csproj
- src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/MyMappedContext.cs
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog.Tests/LogProviders/SerilogLogProviderLoggingTests.cs
- src/LibLog/LibLog.cs
I was migrating some library code to LibLog that previously directly called Serilog and made heavy use of [destructuring](https://github.com/serilog/serilog/wiki/Structured-Data) and the `var logger = Log.ForContext("SomeKey", SomeValue)` contextual logger and `using (LogContext.PushProperty("RequestId", Request.Id))` ambient logging contexts [features](https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/).
I found this LibLog change useful during the migration.
* A destructure flag has been added to OpenMappedContext like so: `IDisposable OpenMappedContext(string key, object value, bool destructure = false);`
* The type of the value parameter changed from string to object.
* The intent is that all exiting code in the world using LibLog should …
> Mapped context destructuring

- src/LibLog.Tests/LogProviderTests.cs
- src/LibLog/LibLog.cs
There is no reason to perform the computation in ResolveLogProvider more than once. In this pull request, I cache the result of the computation of ResolveLogProvider using the Lazy<> class. If someone really wants to call this method again, he can call the internal variant named ForceResolveLogProvider.
See also [this issue](https://github.com/Code-Sharp/WampSharp/pull/202).
> Optimizing calls to ResolveLogProvider()

- src/LibLog.Tests.NLog4/LibLog.Tests.NLog4.csproj
- src/LibLog.Tests.NLog4/packages.config
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog/LibLog.cs
Attempt to fix  #129
Maybe same idea can be applied to log4net, so #97 can also be fixed.
> LibLog - Support NLog callsite without always creating StackTrace

- src/LibLog/LibLog.cs
* Provide empty array for empty params argument;
* Add overloads accepting 1, 2 and 3 format parameters for Trace, Debug and Information logging. Overloads will check if log level is enabled before calling main method
> Optimize memory allocations

- src/LibLog/LibLog.cs
added `global::`-prefix to usings, to avoid collisions in `using`.
:beers:
> added global-prefix to usings

- src/LibLog/LibLog.cs
If we do 'clean up' on a project or solution we don't want resharper touching this file and splitting it into separate classes for instance.
> Disable resharper formatting of this file

- src/LibLog/LibLog.cs
Reused the trick for NLog callsite (#142) to dynamically resolve log4net stack-boundary-type. Resolves #97 
And also did some minor allocation optimizations.
> LibLog - Support dynamic Log4net callerStackBoundaryType 

- src/LibLog.Tests/LibLog.Tests.csproj
- src/LibLog.Tests/LogProviders/LoupeLogProviderLoggingTests.cs
Update Loupe reference to version 4.5.1 which supports a message event to provide all message types and facilitate unit testing, then filled out tests.
> #26 - Add log message tests for Loupe Agent

- src/LibLog/ILogProvider.cs
- src/LibLog/ILogProvider.cs.pp
Using 5.0.2 I get an error when compiling (I have warnings as errors):
[CS1573](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573) - Parameter 'parameter' has no matching param tag in the XML comment for 'parameter' (but other parameters do)
Although the interface is internal (I define LIBLOG_PROVIDERS_ONLY), the warning is still raised as one of the parameters is missing the XML documentation.
> Fix CS1573

- src/LibLog.Example.Library/LibLog.Example.Library.csproj
- src/LibLog.Example.ProvidersOnly/LibLog.Example.ProvidersOnly.csproj
- src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs
- src/LibLog/LogProviders/NLogLogProvider.cs
NLog 4.6 includes better handling of non-string-objects: NLog/NLog#2857
> NLog MDLC + NDLC when NLog ver. 4.6 is ready

- src/LibLog/LogExtensions.cs
- src/LibLog/LogExtensions.cs.pp
- src/LibLog/LogProviders/LibLogException.cs.pp
- src/LibLog/LogProviders/LogMessageFormatter.cs.pp
- src/LibLog/LogProviders/LogProviderBase.cs
- src/LibLog/LogProviders/LogProviderBase.cs.pp
- src/LibLog/LoggerDelegate.cs.pp
Similar to #185 , this adds more XML comments, this time to members which are publicly visible with the LIBLOG_PUBLIC option set, and for the same reason: avoiding 80+ CS1591 warnings when compiling projects that include LibLog and use this option.
(While doing this, I also removed some efficiency logging extension methods - non-params versions redundant with the params versions - since in this case, they just shuffle the params array creation slightly down the call stack. This should cause no change in compilation behavior, and all tests still pass.)
> More XML comments for public members

- src/LibLog/LibLog.csproj
- src/LibLog/LibLog.nuspec
- src/LibLog/LogProvider.cs
- src/LibLog/LogProvider.cs.pp
- src/LibLog/LogProviders/Log4NetLogProvider.cs
- src/LibLog/LogProviders/Log4NetLogProvider.cs.pp
- src/LibLog/LogProviders/NLogLogProvider.cs
- src/LibLog/LogProviders/NLogLogProvider.cs.pp
This should remove the need for a dependency on dynamic and Microsoft.CSharp as discussed in #160
> Replace all usages of dynamic with delegates
